name: Push - Build

on:
  push:

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Node Packages
        run: npm ci --no-fund
      - name: Setup Keystore
        env:
          APP_RELEASE_STORE_PASSWORD: ${{ secrets.APP_RELEASE_STORE_PASSWORD  }}
          APP_RELEASE_KEY_PASSWORD: ${{ secrets.APP_RELEASE_KEY_PASSWORD  }}
        run: |
          cd android
          echo APP_RELEASE_STORE_FILE=ci.keystore >> gradle.properties
          echo APP_RELEASE_KEY_ALIAS=ci-key-alias >> gradle.properties
          echo APP_RELEASE_STORE_PASSWORD=$APP_RELEASE_STORE_PASSWORD >> gradle.properties
          echo APP_RELEASE_KEY_PASSWORD=$APP_RELEASE_KEY_PASSWORD >> gradle.properties
          cd ..

      - name: Build Android App
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
