name: Release

on:
  release:
    types: [published]

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Node Packages
        run: npm ci --no-fund
      - name: Set up Keystore
        run: |
          cd android
          echo "${{ secrets.APP_RELEASE_RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase ${{ secrets.APP_RELEASE_RELEASE_KEYSTORE_PASSPHRASE }} --batch release.keystore.asc > app/release.keystore
          echo APP_RELEASE_STORE_FILE=release.keystore >> gradle.properties
          echo APP_RELEASE_KEY_ALIAS=release-key-alias >> gradle.properties
          echo APP_RELEASE_STORE_PASSWORD=${{ secrets.APP_RELEASE_RELEASE_STORE_PASSWORD  }} >> gradle.properties
          echo APP_RELEASE_KEY_PASSWORD=${{ secrets.APP_RELEASE_RELEASE_KEY_PASSWORD  }} >> gradle.properties
          cd ..
      - name: Build Android App
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
